// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziuzxbzhbgnkztzpjlpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppdXp4YnpoYmdua3p0enBqbHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNTAyNDksImV4cCI6MjA4NjkyNjI0OX0._Iw-YpTCP_HUFKLqBEKSFIWJ_3Q7qLKywrHXqyV7PmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});